#!/usr/bin/env python3

"""Tests for the shared YAML config validation compatibility facade.

These entry points no longer own validation rules: they delegate to the
canonical definition validator and render its diagnostics, keeping only the
historical ``list[str]`` shape (plus the environment-only executable-path check).
The exact messages therefore come from the canonical resolvers, not from a
second copy of the rules.
"""

from __future__ import annotations

from confflow.shared.config_validation import validate_step_config, validate_yaml_config


def test_validate_yaml_config_accepts_minimal_valid_config() -> None:
    errors = validate_yaml_config(
        {
            "global": {"cores_per_task": "2", "max_parallel_jobs": 1},
            "steps": [
                {
                    "name": "gen",
                    "type": "confgen",
                    "params": {"chains": ["1-2-3-4"], "angle_step": 120},
                },
                {
                    "name": "sp",
                    "type": "calc",
                    "params": {"iprog": "orca", "itask": "sp", "keyword": "HF STO-3G"},
                },
            ],
        }
    )

    assert errors == []


def test_validate_yaml_config_reports_root_and_global_errors(tmp_path) -> None:
    missing = tmp_path / "missing-orca"
    errors = validate_yaml_config(
        {
            "global": {
                "gaussian_path": str(missing),
                "orca_path": "orca",
                "cores_per_task": 0,
                "max_parallel_jobs": "many",
            },
            "steps": "not-a-list",
        }
    )

    assert f"Gaussian path not found: {missing}" in errors
    assert "global: cores_per_task must be >= 1, got 0" in errors
    assert "steps: workflow config 'steps' must be a list" in errors


def test_validate_yaml_config_reports_required_sections_and_type_errors() -> None:
    assert validate_yaml_config({}, required_sections=["global"]) == [
        "missing required section: 'global'"
    ]
    assert validate_yaml_config({"global": [], "steps": [None]}) == [
        "global: global config must be a mapping",
        "steps[1]: step must be a mapping",
    ]


def test_validate_step_config_reports_invalid_step_fields() -> None:
    errors = validate_step_config({"params": []}, 0)

    # Names are generated by ConfFlow, so a missing name is not an error; a
    # missing/unsupported type and non-mapping params still are.
    assert "steps[1].type: step 1 has unsupported type: ''" in errors
    assert "steps[1].params: step params must be a mapping" in errors


def test_validate_step_config_reports_calc_errors() -> None:
    errors = validate_step_config(
        {
            "name": "bad_calc",
            "type": "calc",
            "params": {"iprog": "orca", "itask": "bad"},
        },
        1,
    )

    assert "steps[1].params: Unsupported calc task: bad" in errors

    missing_keyword = validate_step_config(
        {
            "name": "no_keyword",
            "type": "calc",
            "params": {"iprog": "orca", "itask": "sp"},
        },
        1,
    )
    assert "steps[1].params: calc step requires a non-empty keyword" in missing_keyword

    iprog_errors = validate_step_config(
        {
            "name": "bad_prog",
            "type": "task",
            "params": {"iprog": "xtb", "itask": 4, "keyword": "opt"},
        },
        2,
    )
    assert "steps[1].params: Unsupported calc program: xtb" in iprog_errors


def test_validate_step_config_reports_confgen_errors() -> None:
    pair_errors = validate_step_config(
        {
            "name": "bad_gen",
            "type": "gen",
            "params": {"chains": ["1-2"], "add_bond": "1"},
        },
        3,
    )
    assert any("pair format error" in error for error in pair_errors)

    angle_errors = validate_step_config(
        {
            "name": "bad_gen",
            "type": "gen",
            "params": {"chains": ["1-2"], "angle_step": "not-a-number"},
        },
        3,
    )
    assert any("angle_step" in error for error in angle_errors)


def test_validate_step_config_accepts_pair_list_variants() -> None:
    for value in ("1 2", [1, 2], [[1, 2], [3, 4]], ["1 2", "3-4"], []):
        errors = validate_step_config(
            {
                "name": "gen",
                "type": "confgen",
                "params": {"chains": ["1-2"], "add_bond": value},
            },
            0,
        )
        assert errors == []


def test_validate_step_config_reports_invalid_type() -> None:
    assert validate_step_config({"name": "x", "type": "viz", "params": {}}, 0) == [
        "steps[1].type: step 1 has unsupported type: 'viz'"
    ]
