#!/usr/bin/env python3
"""Generate and compare the reproducible ConfFlow development locks.

The interpreter paths and the uv executable are deliberately pinned here.  Run
``--write`` to regenerate all Linux x86_64 development locks, or ``--check``
to compile into a temporary directory and compare the normalized contents
without changing a checked-in lock.
"""

from __future__ import annotations

import argparse
import difflib
import subprocess
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UV = Path("/tmp/confflow-uv-0.11.5/uv")
PLATFORM = "x86_64-unknown-linux-gnu"
LOCK_DIR = ROOT / "requirements" / "locks"

TARGETS = {
    "py310": (
        Path(".uv-python/cpython-3.10.20-linux-x86_64-gnu/bin/python"),
        "confflow-dev-py310-linux_x86_64.txt",
        "3.10",
    ),
    "py311": (
        Path(".uv-python/cpython-3.11.15-linux-x86_64-gnu/bin/python"),
        "confflow-dev-py311-linux_x86_64.txt",
        "3.11",
    ),
    "py312": (
        Path(".venv-py312/bin/python"),
        "confflow-dev-py312-linux_x86_64.txt",
        "3.12",
    ),
    "py313": (
        Path(".uv-python/cpython-3.13.13-linux-x86_64-gnu/bin/python"),
        "confflow-dev-py313-linux_x86_64.txt",
        "3.13",
    ),
}


def run(command: Sequence[str], *, cwd: Path | None = None) -> str:
    result = subprocess.run(
        list(command),
        cwd=cwd,
        check=True,
        text=True,
        capture_output=True,
    )
    return result.stdout.strip()


def validate_toolchain() -> None:
    if not UV.is_file() or not UV.stat().st_mode & 0o111:
        raise SystemExit(f"fixed uv executable is missing or not executable: {UV}")
    uv_version = run((str(UV), "--version"))
    if uv_version != "uv 0.11.5 (x86_64-unknown-linux-gnu)":
        raise SystemExit(f"expected fixed uv 0.11.5, got: {uv_version}")
    for name, (relative_path, _, expected_minor) in TARGETS.items():
        interpreter = ROOT / relative_path
        if not interpreter.is_file() or not interpreter.stat().st_mode & 0o111:
            raise SystemExit(f"{name} interpreter is missing or not executable: {interpreter}")
        version = run((str(interpreter), "--version"))
        if not version.startswith(f"Python {expected_minor}."):
            raise SystemExit(f"{name} expected Python {expected_minor}, got: {version}")


def compile_lock(interpreter: Path, output: Path, *, upgrade: bool = False) -> None:
    relative_interpreter = interpreter.relative_to(ROOT)
    command = [
        str(UV),
        "--quiet",
        "pip",
        "compile",
        "pyproject.toml",
        "--extra",
        "dev",
        "--generate-hashes",
        "--python",
        str(relative_interpreter),
        "--python-platform",
        PLATFORM,
        "--output-file",
        str(output.relative_to(ROOT)) if output.is_relative_to(ROOT) else str(output),
    ]
    if upgrade:
        command.append("--upgrade")
    subprocess.run(command, cwd=ROOT, check=True)


def normalized_lock(path: Path) -> list[str]:
    lines = path.read_text(encoding="utf-8").splitlines(keepends=True)
    # uv embeds the output path in the two-line provenance header.  The target
    # path is intentionally different during --check, so compare the lock
    # body while still retaining and validating the header in --write output.
    if len(lines) < 2 or not lines[0].startswith("# This file was autogenerated by uv"):
        raise SystemExit(f"lock has no uv provenance header: {path}")
    if not lines[1].startswith("#    uv pip compile "):
        raise SystemExit(f"lock has no uv compile command header: {path}")
    return lines[2:]


def write_locks(*, upgrade: bool) -> None:
    LOCK_DIR.mkdir(parents=True, exist_ok=True)
    for name, (relative_interpreter, filename, _) in TARGETS.items():
        output = LOCK_DIR / filename
        print(f"generating {name}: {output.relative_to(ROOT)}")
        compile_lock(ROOT / relative_interpreter, output, upgrade=upgrade)
        normalized_lock(output)


def check_locks() -> None:
    missing = [
        filename for _, (_, filename, _) in TARGETS.items() if not (LOCK_DIR / filename).is_file()
    ]
    if missing:
        raise SystemExit("missing lock(s): " + ", ".join(missing))
    with tempfile.TemporaryDirectory(prefix="confflow-lock-check-") as temporary:
        temporary_root = Path(temporary)
        for name, (relative_interpreter, filename, _) in TARGETS.items():
            expected = LOCK_DIR / filename
            generated = temporary_root / filename
            print(f"checking {name}: {expected.relative_to(ROOT)}")
            # uv reuses pins from an existing output file unless --upgrade is
            # requested.  Seed the temporary output to check the exact lock
            # (versions and hashes) without mutating the checked-in file.
            generated.write_bytes(expected.read_bytes())
            compile_lock(ROOT / relative_interpreter, generated)
            expected_body = normalized_lock(expected)
            generated_body = normalized_lock(generated)
            if expected_body != generated_body:
                diff = difflib.unified_diff(
                    expected_body,
                    generated_body,
                    fromfile=str(expected),
                    tofile=str(generated),
                    n=3,
                )
                sys.stderr.write("".join(list(diff)[:80]))
                raise SystemExit(f"lock differs: {expected.relative_to(ROOT)}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group(required=True)
    modes.add_argument("--write", action="store_true", help="regenerate all four lock files")
    modes.add_argument(
        "--check", action="store_true", help="compare fresh locks without changing files"
    )
    parser.add_argument(
        "--upgrade",
        action="store_true",
        help="allow dependency upgrades; only valid with --write",
    )
    args = parser.parse_args()
    if args.upgrade and not args.write:
        parser.error("--upgrade requires --write")
    return args


def main() -> None:
    args = parse_args()
    validate_toolchain()
    if args.write:
        write_locks(upgrade=args.upgrade)
    else:
        check_locks()


if __name__ == "__main__":
    main()
